version: 2
jobs:
  build:
    docker:
      - image: bradfordcp/fedora-gcloud-hugo:31
    working_directory: /root/hugo
    environment:
      HUGO_BUILD_DIR: /root/hugo/public
      HUGO_ENV: production
    steps:
      - checkout
      - attach_workspace:
          at: /root/hugo
      - run:
          name: Configure submodules
          command: git submodule sync && git submodule update --init
      - run:
          name: Build the site with Hugo
          command: hugo -v -d $HUGO_BUILD_DIR
      - persist_to_workspace:
          root: /root/hugo
          paths: public
  deploy_github:
    docker:
      - image: bradfordcp/fedora-gcloud-hugo:31
    working_directory: /root/hugo
    environment:
      HUGO_BUILD_DIR: /root/hugo/public
    steps:
      - checkout
      - run:
          name: Configure submodules
          command: git submodule sync && git submodule update --init
      - attach_workspace:
          at: /root/hugo
      - deploy:
          name: Deploy to GitHub Pages
          command: |
            .circleci/configure_git.sh
            cd $HUGO_BUILD_DIR
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              git status
              git add .
              git commit -m "Built site for $CIRCLE_SHA1"
              git push origin master
            fi
  
  deploy_gcloud:
    docker:
      - image: bradfordcp/fedora-gcloud-hugo:31
    working_directory: /root/hugo
    environment:
      HUGO_BUILD_DIR: /root/hugo/public
    steps:
      - checkout
      - run:
          name: Configure submodules
          command: git submodule sync && git submodule update --init
      - attach_workspace:
          at: /root/hugo
      - deploy:
          name: Deploy to Google Cloud
          command: |
            .circleci/configure_gcloud.sh
            cd $HUGO_BUILD_DIR
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              gsutil -m rsync -r -d . gs://bradfordcp.io/
            else
              echo "Not master branch, dry run only"
              gsutil -m rsync -r -d -n . gs://bradfordcp.io/
            fi

workflows:
  version: 2
  default:
    jobs:
      - build
      - deploy_github:
          requires:
            - build
      - approval:
          type: approval
          requires:
            - deploy_github
      - deploy_gcloud:
          requires:
            - approval
